### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by batwicket** [czycha/example-jest-puppeteer-express-webpack#1]
I'm trying to add typescript support but so far no luck. Any ideas appreciated. There is an issue at [https://stackoverflow.com/questions/50957603/how-can-i-test-a-webpack-bundle-containing-typescript-using-jest](url)

**Comment by batwicket** [comment]
Figured it out. The ts-loader is outputting code which requires a slightly different function call. The forked repo has been updated in case anyone is interested.

**Comment by czycha** [comment]
@batwicket This was closed by the time I ever saw it so sorry for not replying initially. Added your fork to the [README](https://github.com/czycha/example-jest-puppeteer-express-webpack#readme) in case someone would like to use it as a reference!
